In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from api_keys import gmaps_key

In [6]:
# Import clean car data
car_data_df = pd.read_csv("../DataSource/clean_car_data.csv")
car_data_df.head()

,Unnamed: 0,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,2020 Census Tract
0,1,5YJXCBE27J,Island,Greenbank,WA,98253,2018,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,10.0,326880081,(-122.575569 48.08489),5.302997e+10
1,8,1N4BZ0CP8H,Chelan,Wenatchee,WA,98801,2017,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,107,12.0,192768747,(-120.336499 47.425146),5.300796e+10
2,10,WVWKR7AU3K,Snohomish,Edmonds,WA,98026,2019,VOLKSWAGEN,E-GOLF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,125,32.0,477565112,(-122.333046 47.829439),5.306105e+10
3,11,5YJ3E1EB0J,Island,Clinton,WA,98236,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,10.0,476402678,(-122.35803 47.9796),5.302997e+10
4,13,5YJ3E1EBXL,Snohomish,Brier,WA,98036,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322,1.0,103288153,(-122.281856 47.811678),5.306105e+10

In [45]:
# Create a new dataframe to hold only the data that I plan to use
reduced_car_data_df = car_data_df[["City", "Vehicle Location"]]
reduced_car_data_df.head()

        City          Vehicle Location
0  Greenbank    (-122.575569 48.08489)
1  Wenatchee   (-120.336499 47.425146)
2    Edmonds   (-122.333046 47.829439)
3    Clinton      (-122.35803 47.9796)
4      Brier   (-122.281856 47.811678)

In [54]:
# Groupby Location (count)
heat_data_df = reduced_car_data_df.groupby(reduced_car_data_df["Vehicle Location"], as_index=False).count()
heat_data_df.head()

           Vehicle Location  City
0     (-102.69968 22.95716)     7
1      (-117.06882 47.7251)    20
2     (-117.07351 47.22679)     3
3       (-117.0768 46.9101)     9
4   (-117.083224 47.660645)   114

In [56]:
# Reduce to significant data (>1500 for test, use ~200 on Actual)
filtered_heat_data_df = heat_data_df.loc[heat_data_df['City'] > 1500]
filtered_heat_data_df.head()

             Vehicle Location  City
211   (-122.042724 47.623594)  1539
224   (-122.122018 47.678465)  2802
228   (-122.132064 47.759381)  1626
230   (-122.151342 47.560192)  1798
239   (-122.188994 47.678406)  2018

In [57]:
# Extract Vehicle Location into useable tuples
#complete_heat_data_df = pd.merge(filtered_heat_data_df, filtered_heat_data_df["Vehicle Location"].str.split(' ', expand=True), how="left", on=['index', 'index'])

In [31]:
# Configure the map plot
gmaps.configure(api_key= gmaps_key)
heatMapBase = gmaps.figure(center= (47.5, -120), zoom_level= 6.5)

# Add the heatmap layer
#heatMapLayer = gmaps.heatmap_layer(heat_data_df["Vehicle Location"], weights= heat_data_df["City"], dissipating= False, max_intensity= 10, point_radius= 1)
#heatMapBase.add_layer(heatMapLayer)

# Display the map
heatMapBase

ValueError: too many values to unpack (expected 2)